version: '3.1'
services:
  stats-server:
    container_name: stats-server
    build: ewm-stats-service/stats-server
    image: ewm-stats-service/stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=explore

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=explore

  ewm-service:
    container_name: emw-service
    build: ewm-main-service
    image: ewm-main-service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
